export const APP_NAME = 'kiezmarie'
export const CAPITALIZED_APP_NAME = 'Kiezmarie'
export const BUSINESS_NAME = 'Kiezmarie GbR'
export const DOMAIN_NAME = 'kiezmarie.com'
export const EMAIL_ADDRESS = 'nina(at)' + DOMAIN_NAME
export const WWW_DOMAIN_NAME = 'www.' + DOMAIN_NAME
export const CITIES_SUBPATH = 'cities'
export const SHOPS_SUBPATH = 'shops'
export const PATH_SEPARATOR = '/'
