import { Offer } from './offer';

export const OFFERS: Offer[] = [
{
  id: '1',
  businessName: 'Goldener Karpfen',
  businessCategory: 'Restaurant/Café',
  ownerName: 'Herbert Obermayer',
  description: 'Genießen Sie traditionelle bayrische Küche im stilvollen Ambiente. Für unsere Gerichte verwenden wir ausschließlich Zutaten lokaler Herkunft.',
  quote: 'Do legst di nieda!',
  pictureURLs: ['../../assets/shops/1.png'],
  ownerPictureURL: '../../assets/owners/1.png',
  streetAndNumber: 'Lessingstraße 71',
  zipCodeAndCity: '80333 3',
  cityID: '3'
},
{
  id: '2',
  businessName: 'Haargenau',
  businessCategory: 'Dienstleistung',
  ownerName: 'Susie Junghans',
  description: 'Unser Friseurladen lebt von unsere Kunden. Wir lieben moderne und freche Haarschnitte und unsere Kunden auch! Überzeugen Sie sich auch nach der Krise von unserer Kompetenz und unserem modernen Ambiente.',
  quote: 'Kommen Sie vorbei und verpassen sich einen neuen Look!',
  pictureURLs: ['../../assets/shops/2.png'],
  ownerPictureURL: '../../assets/owners/2.png',
  streetAndNumber: 'Salonweg  3b',
  zipCodeAndCity: '50996 4',
  cityID: '4'
},
{
  id: '3',
  businessName: 'Rosgartenmuseum',
  businessCategory: 'Kulturstätten',
  ownerName: 'Maria Flora',
  description: 'Unser Museum ist schon ein fester Bestandteil dieses Stadtkerns seit ich denken kann. Meine Mutter hat mich in die Kunst der Museumsführung eingewiesen und das will ich auch an meine Kinder weitergeben. ',
  quote: 'Rosgartenmuseum - bestes Museum in Hamburg!',
  pictureURLs: ['../../assets/shops/3.png'],
  ownerPictureURL: '../../assets/owners/3.png',
  streetAndNumber: 'Tulpenstraße 9',
  zipCodeAndCity: '20146 1',
  cityID: '1'
},
{
  id: '4',
  businessName: 'Bahnhofskiosk',
  businessCategory: 'Sonstiges',
  ownerName: 'Tom Marcello',
  description: 'In verkaufe schon seit 30 Jahren Kaugummi, Mickey Mouse Hefte und Postkarten. Gerade nutze ich die ruhige Zeit und versuche mein Geschäftskonzept auch auf Teetassen auszuweiten.',
  quote: 'Hilf mir, auch nach der Krise weiterhin Deine Lieblingskaugummis zu verkaufen!',
  pictureURLs: ['../../assets/shops/4.png'],
  ownerPictureURL: '../../assets/owners/4.png',
  streetAndNumber: 'Bahnhofsstraße 12a',
  zipCodeAndCity: '10115 2',
  cityID: '2'
},
{
  id: '5',
  businessName: 'Silbernes Reh',
  businessCategory: 'Restaurant/Café',
  ownerName: 'Gülcan Öztürk',
  description: 'Schon als Kind bin ich an diesem uraltwürdigen Gebäude vorbei gelaufen und wollte unbedingt dort arbeiten. Vor zwei Jahren habe ich das Restaurant vom Vorbesitzer übernommen und biete seitdem Gerichte aus aller Welt an.',
  quote: 'Bitte helft mir, damit wir hier nach Krise wieder in Gesellschaft speisen können.',
  pictureURLs: ['../../assets/shops/5.png'],
  ownerPictureURL: '../../assets/owners/5.png',
  streetAndNumber: 'Hofbräustraße 8',
  zipCodeAndCity: '81929 3',
  cityID: '3'
},
{
  id: '6',
  businessName: 'Beautiful Nails',
  businessCategory: 'Dienstleistung',
  ownerName: 'Tina Ostermann',
  description: 'Wer will schon mit hässlichen Fingernägeln durch die Gegend laufen! Schöne Nägel sind Ausdruck von Modernität und Lebensfreude. Und ein Schwätzchen halten wir auch immer mit unseren Kunden. Ich liebe mein Nagelstudio!',
  quote: 'Kein Nagelstudio, großes Problem!',
  pictureURLs: ['../../assets/shops/6.png'],
  ownerPictureURL: '../../assets/owners/6.png',
  streetAndNumber: 'Lackstraße 55',
  zipCodeAndCity: '50937 4',
  cityID: '4'
},
{
  id: '7',
  businessName: 'Kino Scala',
  businessCategory: 'Kulturstätten',
  ownerName: 'Hermann Prinz',
  description: 'Kino bietet die Möglichkeit, einmal von seinen Alltagsproblemen loszulassen und in eine komplett andere Welt abzutauchen. Kino verändert unseren Blick auf die Welt. Das möchte ich den Menschen auch weiterhin bieten. ',
  quote: 'Großes Kino auch nach der Krise!',
  pictureURLs: ['../../assets/shops/7.png'],
  ownerPictureURL: '../../assets/owners/7.png',
  streetAndNumber: 'Markstätte 1',
  zipCodeAndCity: '22307 1',
  cityID: '1'
},
{
  id: '8',
  businessName: 'Blumenladen Emma',
  businessCategory: 'Boutique/ Warengeschäft',
  ownerName: 'Emma Wiechert',
  description: 'Unser Blumenladen bietet unseren Kunden schon seit 10 Jahren die Antwort auf die Frage: "Was soll ich bloß meinen Liebsten zum Ehrentag schenken?". Gerade in der jetzigen Zeit können wir dies leider nicht mehr umsetzen.',
  quote: 'Bitte helft uns, damit Berlin auch nach der Krise noch bunt geschmückt bleibt.',
  pictureURLs: ['../../assets/shops/8.png'],
  ownerPictureURL: '../../assets/owners/8.png',
  streetAndNumber: 'Tortenweg 28',
  zipCodeAndCity: '10629 2',
  cityID: '2'
},
{
  id: '9',
  businessName: 'Tanzschule Zaunmeister',
  businessCategory: 'Dienstleistung',
  ownerName: 'Mirco Zaunmeister',
  description: 'Wir bringen unseren Kunden alles bei, von Hip Hop über Latein und Standardtänze wie Walzer ist alles dabei. Aktuell drehen wir Videos, damit unsere Kunden sich auch zu Hause fit halten können. ',
  quote: 'Tanzen macht Freude und wir freuen uns schon darauf, wenn wir endlich wieder aufmachen!',
  pictureURLs: ['../../assets/shops/9.png'],
  ownerPictureURL: '../../assets/owners/9.png',
  streetAndNumber: 'Pfauenplatz 45',
  zipCodeAndCity: '81928 3',
  cityID: '3'
},
{
  id: '10',
  businessName: 'Harry`s Eck',
  businessCategory: 'Bar/Kneipe',
  ownerName: 'Harry Dingert',
  description: 'Die gemütliche Kneipe an der Ecke - bei uns ist das noch Realität. Seit Jahrzehnten sind wir fester Bestandteil unseres Viertels und bringen Freunde und Fremde bei einem Bier zusammen. Damit wir auch in Zukunft für euch da sein können, setzen wir auf eure Unterstützung.',
  quote: 'Mein Feierabendbier? Nur bei Harry!',
  pictureURLs: ['../../assets/shops/10.png'],
  ownerPictureURL: '../../assets/owners/10.png',
  streetAndNumber: 'Schillerstraße 67',
  zipCodeAndCity: '10405 2',
  cityID: '2'
},
{
  id: '11',
  businessName: 'Tanzmaus',
  businessCategory: 'Bar/Kneipe',
  ownerName: 'Silke Hansen',
  description: 'Bei uns treffen sich Jung und Alt zu einem gemütlichen Feierabendbier und bleiben auch ganz gerne, um die Tanzfläche später unsicher zu machen. Aktuell haben wir geschlossen, hoffen aber, dass es bald weitergeht.',
  quote: 'Gesellschaft ist ohne Gesellschaft nur halb so schön!',
  pictureURLs: ['../../assets/shops/11.png'],
  ownerPictureURL: '../../assets/owners/11.png',
  streetAndNumber: 'Am Eck  29',
  zipCodeAndCity: '22305 1',
  cityID: '1'
},
{
  id: '12',
  businessName: 'Souvenirshop am Hafen',
  businessCategory: 'Sonstiges',
  ownerName: 'Leon Lagowitz',
  description: 'Moin! Wer einen Hamburger Mitbringsel sucht, der ist bei uns richtig. Hier gibt es alles, was das Touristenherz begehrt und alle können ihren Liebsten eine Erinnerung an unsere schöne Hansestadt mitbringen. ',
  quote: 'Souvenirs erinnern an schöne Zeiten mit Familie und Freunden!',
  pictureURLs: ['../../assets/shops/12.png'],
  ownerPictureURL: '../../assets/owners/12.png',
  streetAndNumber: 'Hafenweg 2',
  zipCodeAndCity: '22303 1',
  cityID: '1'
},
{
  id: '13',
  businessName: 'Hautpflege Schneider',
  businessCategory: 'Dienstleistung',
  ownerName: 'Nina  Schneider',
  description: 'Bei uns kommen die Kunden mit einem fahlen Teint und gehen mit strahlender Haut und strahlenden Augen. Wir lassen uns nicht nehmen, unsere Kunden ganzheitlich zu verwöhnen. Das wollen wir auch weiterhin tun. ',
  quote: 'Niemand muss unreine Haut haben. Kommen Sie vorbei und überzeugen Sie sich selbst!',
  pictureURLs: ['../../assets/shops/13.png'],
  ownerPictureURL: '../../assets/owners/13.png',
  streetAndNumber: 'Zahnweg 42',
  zipCodeAndCity: '50932 4',
  cityID: '4'
},
{
  id: '14',
  businessName: 'Bella Ciao',
  businessCategory: 'Restaurant/Café',
  ownerName: 'Adrian Gianno',
  description: 'Unser Café wurde vor 20 Jahren von meinem Vater gegründet. Hier gibt es selbst gemahlenen Café und selbst gebackene italienische Köstlichkeiten. Gerade arbeiten wir an einem neuen Mahlverfahren und einer neuen Cafésorte.',
  quote: 'Unser Café wird bald noch leckerer! Kommen Sie vorbei sobald es geht!',
  pictureURLs: ['../../assets/shops/14.png'],
  ownerPictureURL: '../../assets/owners/14.png',
  streetAndNumber: 'Hansaplatz 9',
  zipCodeAndCity: '10345 2',
  cityID: '2'
  }
];
